on:
  push:
    paths:
      - .github/workflows/build.yml
      - iFamily/**
      - xmake.lua
  pull_request:
    paths:
      - .github/workflows/build.yml 
      - iFamily/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        mode:
          - debug
          - release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p windows -v -y

      - run: |
          xmake -v -w -y

      - run: |
          xmake package -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: iFamily-${{ matrix.mode }}-windows-x64-${{ github.sha }}
          path: |
            build/packages/i/iFamily/windows/x64/${{ matrix.mode }}/

  check-style:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          choco install llvm -y --version=17.0.6

      - run: |
          Get-ChildItem iFamily/ -Filter *.cpp -Recurse | ForEach-Object { clang-format -i -Werror $_.FullName }
          Get-ChildItem iFamily/ -Filter *.h -Recurse | ForEach-Object { clang-format -i -Werror $_.FullName }
