on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        mode:
          - debug
          - release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p windows -v -y

      - run: |
          xmake -v -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.mode }}-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/release/

  clang-format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          choco install llvm -y --version=17.0.6

      - name: clang-format
        run: |
          Get-ChildItem iFamily/ -Filter *.cpp -Recurse | ForEach-Object { clang-format -i -Werror $_.FullName; if ($LASTEXITCODE -ne 0) { exit 1; } }
          Get-ChildItem iFamily/ -Filter *.h -Recurse | ForEach-Object { clang-format -i -Werror $_.FullName; if ($LASTEXITCODE -ne 0) { exit 1; } }
